name: tapin_app
description: "To Track Employees location and attendance"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  geolocator: ^10.1.0
  intl: ^0.17.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.0
  firebase_storage: ^12.4.4
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^1.0.0
  fl_chart: ^0.64.0
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.8
  firebase_auth_web: ^5.8.13
  animated_text_kit: ^4.2.2
  permission_handler: ^11.3.0
  lottie: ^2.6.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tapin_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/tapin_logo.png